package com.caletre.refactoring.toJava8.service;

public enum CinemaTemplateType {
    ALL_AVAILABLE,
	FULL_SCENARIO,
	ONE_SCENARIO,
	TWO_CONSECUTIVE_SCENARIO,
	THREE_CONSECUTIVE_SCENARIO,
	FOUR_CONSECUTIVE_SCENARIO,
	FIVE_CONSECUTIVE_SCENARIO,
	SIX_CONSECUTIVE_SCENARIO,
	TWO_RANDOM_SCENARIO,
	THREE_RANDOM_SCENARIO,
	FOUR_RANDOM_SCENARIO,
	FIVE_RANDOM_SCENARIO,
	SIX_RANDOM_SCENARIO
}
